---
title: "git_00"
author: "Ariana Rodriguez"
date: "4 September, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Little Birds are dining   
Warily and well,  
Hid in mossy cell:  
Hid, I say, by waiters  
Gorgeous in their gaiters-  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

I dwell in a lonely house I know  
That vanished many a summer ago,  
And left no trace but the cellar walls,   
And a cellar in which the daylight falls,    
And the purple-stemmed wild raspberries grow.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright-  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done-  
"It's very rude of him," she said,  
"To come and spoil the fun!"  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

On the Erie Canal, it was,  
All on a summer's day,  
I sailed forth with my parents  
Far away to Albany.  

From out the clouds at noon that day   
There came a dreadful storm,  
That piled the billows high about,  
And filled us with alarm.  

A man came rushing from a house,  
Saying, "Snub up your boat I pray,  
Snub up your boat, snub up, alas,  
Snub up while yet you may."  

Our captain cast one glance astern,  
Then forward glanced he,  
And said, "My wife and little ones  
I never more shall see." 
